/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTransferRouteImport } from './routes/_app.transfer'
import { Route as AppQuestsRouteImport } from './routes/_app.quests'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppMintRouteImport } from './routes/_app.mint'
import { Route as AppLeaderboardRouteImport } from './routes/_app.leaderboard'
import { Route as AppEventsRouteImport } from './routes/_app.events'
import { Route as AppEarnXpRouteImport } from './routes/_app.earn-xp'
import { Route as AppBadgesRouteImport } from './routes/_app.badges'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppActivityRouteImport } from './routes/_app.activity'
import { Route as ApiPublicWalletAuthRouteImport } from './routes/api/public/wallet-auth'
import { Route as AppEventsEventIdRouteImport } from './routes/_app.events.$eventId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransferRoute = AppTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestsRoute = AppQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMintRoute = AppMintRouteImport.update({
  id: '/mint',
  path: '/mint',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppEarnXpRoute = AppEarnXpRouteImport.update({
  id: '/earn-xp',
  path: '/earn-xp',
  getParentRoute: () => AppRoute,
} as any)
const AppBadgesRoute = AppBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicWalletAuthRoute = ApiPublicWalletAuthRouteImport.update({
  id: '/api/public/wallet-auth',
  path: '/api/public/wallet-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AppEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/activity': typeof AppActivityRoute
  '/admin': typeof AppAdminRoute
  '/badges': typeof AppBadgesRoute
  '/earn-xp': typeof AppEarnXpRoute
  '/events': typeof AppEventsRouteWithChildren
  '/leaderboard': typeof AppLeaderboardRoute
  '/mint': typeof AppMintRoute
  '/profile': typeof AppProfileRoute
  '/quests': typeof AppQuestsRoute
  '/transfer': typeof AppTransferRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/api/public/wallet-auth': typeof ApiPublicWalletAuthRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/activity': typeof AppActivityRoute
  '/admin': typeof AppAdminRoute
  '/badges': typeof AppBadgesRoute
  '/earn-xp': typeof AppEarnXpRoute
  '/events': typeof AppEventsRouteWithChildren
  '/leaderboard': typeof AppLeaderboardRoute
  '/mint': typeof AppMintRoute
  '/profile': typeof AppProfileRoute
  '/quests': typeof AppQuestsRoute
  '/transfer': typeof AppTransferRoute
  '/': typeof AppIndexRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/api/public/wallet-auth': typeof ApiPublicWalletAuthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/badges': typeof AppBadgesRoute
  '/_app/earn-xp': typeof AppEarnXpRoute
  '/_app/events': typeof AppEventsRouteWithChildren
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/mint': typeof AppMintRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/quests': typeof AppQuestsRoute
  '/_app/transfer': typeof AppTransferRoute
  '/_app/': typeof AppIndexRoute
  '/_app/events/$eventId': typeof AppEventsEventIdRoute
  '/api/public/wallet-auth': typeof ApiPublicWalletAuthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/activity'
    | '/admin'
    | '/badges'
    | '/earn-xp'
    | '/events'
    | '/leaderboard'
    | '/mint'
    | '/profile'
    | '/quests'
    | '/transfer'
    | '/events/$eventId'
    | '/api/public/wallet-auth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/activity'
    | '/admin'
    | '/badges'
    | '/earn-xp'
    | '/events'
    | '/leaderboard'
    | '/mint'
    | '/profile'
    | '/quests'
    | '/transfer'
    | '/'
    | '/events/$eventId'
    | '/api/public/wallet-auth'
  id:
    | '__root__'
    | '/_app'
    | '/about'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/_app/activity'
    | '/_app/admin'
    | '/_app/badges'
    | '/_app/earn-xp'
    | '/_app/events'
    | '/_app/leaderboard'
    | '/_app/mint'
    | '/_app/profile'
    | '/_app/quests'
    | '/_app/transfer'
    | '/_app/'
    | '/_app/events/$eventId'
    | '/api/public/wallet-auth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiPublicWalletAuthRoute: typeof ApiPublicWalletAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfer': {
      id: '/_app/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof AppTransferRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quests': {
      id: '/_app/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof AppQuestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mint': {
      id: '/_app/mint'
      path: '/mint'
      fullPath: '/mint'
      preLoaderRoute: typeof AppMintRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/earn-xp': {
      id: '/_app/earn-xp'
      path: '/earn-xp'
      fullPath: '/earn-xp'
      preLoaderRoute: typeof AppEarnXpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/badges': {
      id: '/_app/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof AppBadgesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/wallet-auth': {
      id: '/api/public/wallet-auth'
      path: '/api/public/wallet-auth'
      fullPath: '/api/public/wallet-auth'
      preLoaderRoute: typeof ApiPublicWalletAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/events/$eventId': {
      id: '/_app/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppEventsRoute
    }
  }
}

interface AppEventsRouteChildren {
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
}

const AppEventsRouteChildren: AppEventsRouteChildren = {
  AppEventsEventIdRoute: AppEventsEventIdRoute,
}

const AppEventsRouteWithChildren = AppEventsRoute._addFileChildren(
  AppEventsRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAdminRoute: typeof AppAdminRoute
  AppBadgesRoute: typeof AppBadgesRoute
  AppEarnXpRoute: typeof AppEarnXpRoute
  AppEventsRoute: typeof AppEventsRouteWithChildren
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMintRoute: typeof AppMintRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQuestsRoute: typeof AppQuestsRoute
  AppTransferRoute: typeof AppTransferRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAdminRoute: AppAdminRoute,
  AppBadgesRoute: AppBadgesRoute,
  AppEarnXpRoute: AppEarnXpRoute,
  AppEventsRoute: AppEventsRouteWithChildren,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMintRoute: AppMintRoute,
  AppProfileRoute: AppProfileRoute,
  AppQuestsRoute: AppQuestsRoute,
  AppTransferRoute: AppTransferRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiPublicWalletAuthRoute: ApiPublicWalletAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
